# Generated by Django 5.1.5 on 2025-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('powerstrips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('parent_power_strip', models.ManyToManyField(to='powerstrips.parent')),
            ],
        ),
    ]
