# Generated by Django 5.1.5 on 2025-01-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerstrips', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='parent_power_strip',
            field=models.ManyToManyField(blank=True, to='powerstrips.parent'),
        ),
    ]
