# Generated by Django 5.1.5 on 2025-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('child_strips', models.ManyToManyField(to='powerstrips.child')),
            ],
        ),
    ]
