# Generated by Django 5.1.5 on 2025-01-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('powerstrips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('child_strip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerstrips.child')),
            ],
        ),
    ]
