# Generated by Django 5.1.5 on 2026-02-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('powerstrips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='powerstrips.child'),
        ),
        migrations.AddField(
            model_name='device',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.devicetemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('child', 'slot')},
        ),
    ]
