# Generated by Django 5.1.5 on 2026-01-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('powerstrips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('power', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['slot']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='power',
        ),
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='child_strip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='powerstrips.child'),
        ),
        migrations.AddField(
            model_name='device',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devicetemplate'),
        ),
    ]
