# Generated by Django 5.1.5 on 2026-01-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicetemplate_alter_device_options_and_more'),
        ('powerstrips', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('child_strip', 'slot')},
        ),
    ]
