# Generated by Django 5.1.5 on 2026-01-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_unique_together'),
        ('powerstrips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='child_strip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='powerstrips.child'),
        ),
    ]
