# Generated by Django 3.2.6 on 2021-08-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=20)),
                ('cluster_log', models.TextField(blank=True, null=True)),
                ('cluster_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cluster')),
            ],
        ),
    ]
