# Generated by Django 3.2.6 on 2021-08-07 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='cluster_type',
            field=models.CharField(choices=[('R', 'RDC'), ('C', 'CDC'), ('G', 'GC')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
