# Generated by Django 3.2.6 on 2021-08-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_cluster_cluster_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
