# Generated by Django 3.2.6 on 2021-08-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_post_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='CR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_number', models.CharField(max_length=250)),
                ('start_date', models.CharField(default='YYYY-MM-DD', max_length=10)),
                ('end_date', models.CharField(default='YYYY-MM-DD', max_length=10)),
                ('status', models.CharField(choices=[('S', 'SXC'), ('I', 'Infra Leader'), ('A', 'Security'), ('I', 'In Progress'), ('F', 'Finished')], max_length=20)),
            ],
        ),
    ]
