# Generated by Django 3.2.6 on 2021-08-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cr',
            name='status',
            field=models.CharField(choices=[('X', 'SXC'), ('I', 'Infra Leader'), ('S', 'Security'), ('I', 'In Progress'), ('F', 'Finished'), ('N', 'Not Started')], max_length=20),
        ),
    ]
