# Generated by Django 3.2.6 on 2021-08-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_cr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cr',
            name='status',
            field=models.CharField(choices=[('S', 'Security'), ('X', 'SXC'), ('I', 'Infra Leader'), ('N', 'Not Started'), ('I', 'In Progress'), ('F', 'Finished'), ('C', 'Closed')], max_length=20),
        ),
    ]
