# Generated by Django 3.2.6 on 2021-08-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_cr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cr',
            name='end_time',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cr',
            name='start_time',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
